name: Map data cleaning

on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Install kart
      run: |
        curl -L https://github.com/koordinates/kart/releases/download/v0.14.2/kart_0.14.2_amd64.deb -o kart.deb
        sudo dpkg -i kart.deb
    - name: Checkout geopackage
      run: kart clone https://github.com/pf-wikis/mapping-data.git sources
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Download tile-compiler jar
      run: wget https://github.com/pf-wikis/mapping/releases/download/latest-tile-compiler-dummy/tile-compiler.jar
    - name: Clean data
      run: |
        cd sources
        java -jar ../tile-compiler.jar clean
    - name: Push changes if necessary
      run: |
        cd sources
        if [[ "$(kart status)" == *"Nothing to commit"* ]]; then
          echo "Nothing to commit"
        else
          kart remote set-url origin https://x-access-token:${{ secrets.DISPATCH_PAT }}@github.com/${{ github.repository }}
          kart config --global user.name 'Map data cleaning'
          kart config --global user.email '12272732+manuel-hegner@users.noreply.github.com'
          kart commit -m "Cleaning data"
          kart push
        fi
        